version: '3'

services:
  backend:
    image: spring-boot-image
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/compagnie
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2001

  frontend:
    image: react-image
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 2001
      MYSQL_DATABASE: compagnie
      MYSQL_USER: sa
      MYSQL_PASSWORD: azerty
    ports:
      - "3306:3306"
